name: Build and push to aws

on:
    push:
        branches:
            -main


jobs:
    build:
        runs-ons: unbuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkkout@v3

            - name: Setup dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '6.0'

            - name: Build project
              run: dotnet restore; dotnet publish -o site; 

            - name: create zip package
              run: cd site; zip ../site.zip *;

            - name: Deploy to aws EB
              uses: einaregilsson/beanstalk-deploy@21
              with: 
                aws_access_key:
                aws-secret_key:
                enviropment_name:
                version_lanel:
                region:
                deployment_package: site.zip


     
on:
    push:
        branches:
            -main










    
